version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres-local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_local_password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      # Volumen persistente para los datos de la base de datos
      - postgres-data:/var/lib/postgresql/data
      # Copiar el archivo de backup para inicializar la base de datos (solo si es necesario)
      - ./db-scripts/Aniview.sql:/docker-entrypoint-initdb.d/Aniview.sql
    restart: always

  # Aquí puedes añadir otros servicios si es necesario, como tu aplicación Spring Boot.

volumes:
  postgres-data:
    driver: local
